name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Account activity
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          base: activity
          repositories_affiliations: owner, collaborator, organization_member
          repositories_skipped: lifuyue/xmu-java-prog, lifuyue/xmu-cn-lab, lifuyue/xmu-cg-lab, Crloxa/Computer-Network-project-1
          commits_authoring: l1fuyue@icloud.com
          config_timezone: Asia/Shanghai

      - name: OpenClaw contributors
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.contributors.contributions.svg
          base: ""
          template: repository
          user: openclaw
          repo: openclaw
          plugin_contributors: yes
          plugin_contributors_base: b71d8e1c32e3903eed765164287c51cbce446e51
          plugin_contributors_head: main
          plugin_contributors_contributions: yes
          plugin_contributors_ignored: github-actions[bot], dependabot[bot]
          config_timezone: Asia/Shanghai
